[pytest]
filterwarnings =
    ignore:'audioop' is deprecated and slated for removal in Python 3.13:DeprecationWarning:nextcord.player
    ignore:pkg_resources is deprecated as an API:UserWarning:nextcord.health_check
